### ISSUE TITLE
createNewRichmenu can't work

### ISSUE THREAD

**Issue by MetalheadKen** [line/demo-rich-menu-bot#4]
I have already changing the CHANNEL_ACCESS_TOKEN and CHANNEL_SECRET and also use Composer to install the LINE Messaging API SDK.
But when I trying to run this demo bot on my LINE app. It doesn't create any Rich menu and doesn't display any error or warning.
Did I have missed anything?
Thanks.

**Comment by terryds** [comment]
@MetalheadKen I have same issue, have you found any solution?
