### ISSUE TITLE
how to upload image with curl

### ISSUE THREAD

**Issue by yang5664** [line/demo-rich-menu-bot#5]
I'm trying to upload image with curl but doesn't success, always return 
 {"message":"Internal Server Error"}  

Env PHP 7
```
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://api.line.me/v2/bot/richmenu/$menu_id/content');
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, new \CURLFile(realpath($imagepath)));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$headers = ["Authorization: Bearer $channel_access_token"];
$headers = ["Content-Type: image/jpeg"];
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
$result = curl_exec($ch);
if (curl_errno($ch)) {
    \Log::info('Error:' . curl_error($ch));
}
curl_close ($ch);
```

can you help me. please.

**Comment by Xuan-Goldenf** [comment]
I found the anwser

**Comment by mxt305** [comment]
Try to replace
`curl_setopt($ch, CURLOPT_POSTFIELDS, new \CURLFile(realpath($imagepath)));`
with 
`curl_setopt($ch, CURLOPT_POSTFIELDS, file_get_contents(realpath($imagepath)));`

**Comment by Yanghsuanming** [comment]
@mxt305  thank you
final I using official sdk to fix this problem.

**Comment by jsmithangular** [comment]
> final I using official sdk to fix this problem.
can you share your code? how did you fixed that?
